* idea

The idea is that we can convert the asts to json, flatten them into parquet.
this gives us many datasets with different features.

Next we can consider the columns and realize that some of the values also reference the columes.
There is a relationship between columns, and a relationship between columnes and values.

If we vectorize them both, we will find an overlap. We can vectorize the columns and the values and then match them based on that.

This will give us an indication of the areas, or a layout of the data into the vector space.
We will then want to use this information to embed the datasets row by row.
We can cluster the rows together and embed them as well based on cluster.

This should give us some clustering and partitioning.
There will be relationships between different modules and functions as well.

** what we are looking for :

1. descriptions of the fields in the values that match the columns.
   Some of the values will match the columns exactly. We want to basically vectorize them both and join the most similar to each other.

2. longer paths in the fields will be compounds. We can shorten or longen the paths of the fields.

* data collected
python ./reflect.py > ast_json.json
jq . ast_json.json >ast_json_pretty.json
grep "\"_type\"" ast_json_pretty.json  | cut -d: -f2 | sort |uniq -c | sort -n |tail
   2817  "Expr",
   4102  "arg",
   5543  "Assign",
   8700  "Store"
   9233  "Call",
  10076  "Attribute",
  10266  "Tuple",
  40225  "Name",
  55209  "Load"
  66254  "Constant",

 * Some of the relationships, this shows the count, the
   name of the node and the parent context.
     12 Dump Nonlocal function_body
     15 Dump AsyncFunctionDef function_body
     15 Dump Delete module
     15 Dump For module
     20 Dump Assert module
     27 Dump Delete function_body
     28 Dump AsyncFunctionDef class_body
     38 Dump Global function_body
     38 Dump If class_body
     71 Dump Import function_body
    133 Dump Try module
    159 Dump Pass class_body
    159 Dump Pass function_body
    180 Dump AugAssign function_body
    225 Dump AnnAssign module
    246 Dump While function_body
    314 Dump ImportFrom function_body
    341 Dump Raise function_body
    387 Dump With function_body
    396 Dump Assert function_body
    560 Dump If module
    671 Dump Expr module
    
   1086 Dump Try function_body
   1111 Dump AnnAssign function_body
   1722 Dump Expr class_body
   1751 Dump For function_body
   
   1768 Dump AnnAssign class_body
   1788 Dump Assign class_body
   
   2202 Dump Import module
   3017 Dump Assign module
   5061 Dump ImportFrom module

   8177 Dump Return function_body
   8629 Dump If function_body
  10839 Dump Expr function_body
  15382 Dump Assign function_body  
